# 网站基本信息
title: Your Name
description: >-
  大家好，这里是闫思慧的网页
baseurl: "https://wang2025-999.github.io"  # 项目名称（如 https://username.github.io/project-name）
url: "https://wang2025-999.github.io"  # 个人网址

# Jekyll 配置
theme: minima  # 使用的主题
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 导航菜单
header_pages:
  - README.md


# 其他设置
markdown: kramdown
highlighter: rouge
